---
#
# Playbook to launch resources on EC2
#
#

- name: Playbook to launch resources on EC2
  hosts: localhost
  connection: local
  vars_files:
    - vars/aws.yml
    - vars/eks.yml

#  pre_tasks:
#
#    - name: Update OS packages
#      yum:
#        name: '*'
#        state: latest
#      become: true
#      become_method: sudo
#
#    - name: Install Development tools
#      yum:
#        name: '@Development tools'
#        state: present
#      become: true
#      become_method: sudo
#
#    - name: Install Python PIP
#      yum:
#        name: python-pip
#        state: present
#      become: true
#      become_method: sudo
#
#    - name: Install boto packages
#      pip:
#        name: '{{item}}'
#        state: present
#      become: true
#      become_method: sudo
#      with_items:
#        - boto
#        - botocore
#        - boto3

  roles:
#    - { role: test, }
    - { role: vpc_operations, when: vpc_operation is defined }
    - { role: ec2_operations, when: ec2_operation is defined }
    - { role: eks_operations, when: eks_operation is defined }
    - { role: s3_fileops, when: s3_fileop is defined }

