---
#
# Playbook to setup Springboot sample application
#
# Positional arguments:
#
# Tags:
#
#

- name: Playbook to setup Springboot sample application
  hosts: "{{instance_name}}"
  vars_files:
    - vars/aws.yml

  roles:
    - { role: springboot_prereqs, }

