---
#
# Playbook to setup Springboot sample application
#
# Positional arguments:
#
# Tags:
#
#

- name: Playbook to setup Springboot sample application
  hosts: all
  vars_files:
    - vars/aws.yml

  pre_tasks:
    - name: Wait for connection
      wait_for_connection:
        delay: 60
        timeout: 300
    - name: Set env for AWS EC2
      environment:
        region: "{{ec2_region}}"
      delegate_to: localhost

  roles:
    - { role: springboot_prereqs, }

