---
#
# Play for AWS EKS operations
#
# arguments:
#
# tags:
# 
#

- name: Include Create EKS Cluster Task
  include_tasks: create_eks_cluster.yml
  when:
    - eks_operation is defined
    - eks_operation == "create_eks_cluster"

- name: Include Release EKS Cluster Task
  include_tasks: release_eks_cluster.yml
  when:
    - eks_operation is defined
    - eks_operation == "release_eks_cluster"

- name: Include Create EKS NodeGroup Task
  include_tasks: create_eks_worker.yml
  when:
    - eks_operation is defined
    - eks_operation == "create_eks_nodegroup"


