---
#
# Play to perform file operations on AWS S3 bucket
#
#
# Tags:
# s3_upload, s3_download

- name: Upload JDK 1.8.0_172 to AWS S3 bucket
  aws_s3:
    aws_access_key: "{{aws_access_key}}"
    aws_secret_key: "{{aws_secret_key}}"
    bucket: rdurvasula-3rdparty
    object: "/java/jdk-8u172-linux-x64.rpm"
    src: "/root/jdk-8u172-linux-x64.rpm"
    mode: put
    region: "{{region}}"
    metadata: "Content-Type=application/octet-stream"
  become: true
  become_method: sudo
  tags:
    - s3_upload

- name: Download PostgreSQL rpms from S3
  aws_s3:
    aws_access_key: "{{aws_access_key}}"
    aws_secret_key: "{{aws_secret_key}}"
    bucket: rdurvasula-3rdparty
    object: "/postgresql/{{item}}"
    dest: "/root/tmp2/{{item}}"
    mode: get
    region: "{{region}}"
    metadata: "Content-Type=application/octet-stream"
  become: true
  become_method: sudo
  with_items:
    - postgresql96-contrib-9.6.10-1PGDG.rhel7.x86_64.rpm
  tags:
    - s3_download

