---
#
# Task to launch EC2 instance with pre-requisite resources
#
# Arguments:
# ec2_operation = 'launch_instance|release_instance'
# instance_name = <any character>
# sg_name = <any character> (default=instance_name)
# my_public_ip = controller machine's public IP address
# target_subnet_tag = subnet tag name which is attached to EC2 instance
#
# tags:
# launch_ec2_instance
#

- name: Include Provision VPC Task
  include_role:
    - name: vpc_operations
  vars:
    - vpc_operation: "create_vpc"
  tags:
    - launch_ec2_instance

- name: Gather VPC facts
  ec2_vpc_net_facts:
    filters:
      "tag:Name": "{{vpc.name}}"
    region: "{{region}}"
  environment:
    AWS_ACCESS_KEY_ID: "{{aws_access_key}}"
    AWS_SECRET_ACCESS_KEY: "{{aws_secret_key}}"
  register: vpc_details
  tags:
   - launch_ec2_instance

- name: Provision EC2 security group
  ec2_group:
    name: "{{sg_name}}"
    description: 'Security group for {{sg_name}}'
    vpc_id: "{{vpc_details.vpcs[0].id}}"
    region: "{{region}}"
    rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: "{{my_public_ip}}/32"
    tags:
      Name: "{{sg_name}}"
  register: sg_details
  environment:
    AWS_ACCESS_KEY_ID: "{{aws_access_key}}"
    AWS_SECRET_ACCESS_KEY: "{{aws_secret_key}}"
  tags:
   - launch_ec2_instance

- name: Get subnet details by tag
  ec2_vpc_subnet_facts:
    region: "{{region}}"
    filters:
      vpc-id: "{{vpc_details.vpcs[0].id}}"
      "tag:Name": "{{target_subnet_tag}}"
  environment:
    AWS_ACCESS_KEY_ID: "{{aws_access_key}}"
    AWS_SECRET_ACCESS_KEY: "{{aws_secret_key}}"
  register: target_subnet_details
  tags:
   - launch_ec2_instance

- name: Provision EC2 instance
  ec2:
    key_name: irel_keypair1
    vpc_subnet_id: "{{target_subnet_details.subnets[0].id}}"
    assign_public_ip: yes
    group_id: "{{sg_details.group_id}}"
    instance_type: t2.micro
    image: "{{ ami_id }}"
    region: "{{region}}"
    wait: yes
    exect_count: 1
    count_tag:
      Name: Test
    instance_tags:
      Name: "{{instance_name}}"
  register: ec2_instance
  environment:
    AWS_ACCESS_KEY_ID: "{{aws_access_key}}"
    AWS_SECRET_ACCESS_KEY: "{{aws_secret_key}}"
  tags:
   - launch_ec2_instance

